### ISSUE TITLE
How to run in windows

### ISSUE THREAD

**Issue by shifatbuet** [Oseid/Facebom#2]
Getting the following error:  

C:\>cd FB-BrForAttack

C:\FB-BrForAttack>python FB-BrForAttack.py
  File "FB-BrForAttack.py", line 47
    passwfile = open(passw, "r")
                               ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Oseid** [comment]
please redownload the script and try again 

i fix this problem :) 

and if you not install mechanize library please install it :) 

using this command : pip install mechanize

and thanks for using my script :)

**Comment by jasmineramona** [comment]
Contact jasmineramona@protonmail.com if you need facebook hacking help
