### ISSUE TITLE
Same error again and again...

### ISSUE THREAD

**Issue by MrNobodyTharusha** [Oseid/Facebom#3]
When I install it like this-

pip install requests
pip install mechanize

And 

python2 facebom.py

It shows-

$ cd Facebom
$ ls
README.md  facebom.py
$ python2 facebom.py
[!] ImportError: [mechanize] Module Is Missed
[*] Please Install it Using this command> [ pip install mechanize ]
$

**Comment by MrNobodyTharusha** [comment]
Hey I fixed the error

**Comment by MrNobodyTharusha** [comment]
It is a small error but if you update the instructions like this -

pip2 install requests
pip2 install mechanize

    - it will be better for new hackers...  😊😊😊😊

**Comment by Oseid** [comment]
> It is a small error but if you update the instructions like this -
> 
> $pip2 install requests
> $pip2 install mechanize
> 
> ```
> - it will be better for new hackers...  😊😊😊😊
>

**Comment by Oseid** [comment]
sorry i have fixed the script can you redownload it or you can run
this command in script folder: git pull 
and thanks for usage

**Comment by Oseid** [comment]
Don't Forget to use python2.7 or if you using android termux app you can install python2 only :)

if you using termux run this commands

pkg update
pkg install python2
pip2 install requests
pip2 install mechanize

to run script do 
python2 facebom.py

and the script will run without any problem :)

**Comment by MrNobodyTharusha** [comment]
Its ok bro...  :-)
