### ISSUE TITLE
Proxy wont connect

### ISSUE THREAD

**Issue by Fr0ntalF8** [Oseid/Facebom#7]
Here is the output
[~] Connecting To Proxy[ 35.236.37.121 ]...
[Connection Failed] !!!

[!] Error: Invalid HTTP/S Proxy[35.236.37.121] !!!

**Comment by Fr0ntalF8** [comment]
Figured it out, used a proxy from https://www.us-proxy.org/

**Comment by jasmineramona** [comment]
Contact jasmineramona@protonmail.com if you need facebook hacking help
